"use client";
import { useState, useEffect } from "react";
import { loadDB, saveDB, TIRAGES, GlobalDB } from "../lib/db";
export default function Proprio(){
 const [db,setDb]=useState<GlobalDB|null>(null); const [tab,setTab]=useState("Vendeurs"); const [selTiraj,setSelTiraj]=useState("GA midi");
 useEffect(()=>{ setDb(loadDB()); },[]); if(!db) return <div style={{padding:20}}>Chargement baz V4...</div>;
 const up=(fn:any)=>{ const nd={...db}; fn(nd); setDb(nd); saveDB(nd); };
 return (<div style={{maxWidth:500,margin:'0 auto',background:'#fff',color:'#000',minHeight:'100vh',padding:10}}>
  <div style={{border:'3px solid #000',borderRadius:12,padding:12,textAlign:'center',fontWeight:900}}>PROPRIO - MENM BAZ V4 - {db.antet.nom}</div>
  <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr 1fr',gap:6,marginTop:10}}>
   {["Vendeurs","Limite","Fermeture","Prix","Rapport","Résultats","Entête","Param"].map(t=><button key={t} onClick={()=>setTab(t)} style={{padding:12,border:'2px solid #000',borderRadius:10,fontWeight:900,fontSize:10,background:tab===t?"#4fb3ff":"#eee"}}>{t}</button>)}
  </div>

  {tab==="Vendeurs" && <div style={{border:'2px solid #000',borderRadius:10,padding:10,marginTop:10}}>
   <b>Gestion Vendeurs - Non - modpas - % - ouvert/fermé - X</b>
   <input placeholder="Non vendeur" id="nvNom" style={{width:'100%',padding:12,border:'2px solid #000',borderRadius:8,marginTop:8}}/>
   <div style={{display:'flex',gap:6,marginTop:6}}><input placeholder="Modpas" id="nvPass" style={{flex:1,padding:12,border:'2px solid #000',borderRadius:8}}/><input placeholder="%" id="nvPou" defaultValue="20" style={{width:60,padding:12,border:'2px solid #000',borderRadius:8}}/><button onClick={()=>{ const nom=(document.getElementById('nvNom') as any).value; const modpas=(document.getElementById('nvPass') as any).value; const pou=(document.getElementById('nvPou') as any).value; if(!nom) return alert("Mete non"); up((d:any)=>d.vendeurs.push({id:Date.now(),proprioId:1,nom,modpas,serie:"SERIE-"+Date.now().toString().slice(-4),pou,statut:"Aktif"})); (document.getElementById('nvNom') as any).value=""; }} style={{background:'#0d7a3e',color:'#fff',padding:12,borderRadius:8,fontWeight:900}}>＋</button></div>
   {db.vendeurs.map((v:any)=><div key={v.id} style={{display:'flex',justifyContent:'space-between',padding:8,borderBottom:'1px solid #000',fontSize:12,fontWeight:900}}><span>{v.nom} {v.modpas} {v.pou}%</span><div><button onClick={()=>up((d:any)=>{ const f=d.vendeurs.find((x:any)=>x.id===v.id); if(f) f.statut=f.statut==="Aktif"?"Bloke":"Aktif" })} style={{marginRight:6}}>{v.statut}</button><button onClick={()=>up((d:any)=>d.vendeurs=d.vendeurs.filter((x:any)=>x.id!==v.id))} style={{background:'red',color:'#fff',border:'none',padding:'4px 8px',borderRadius:6}}>X</button></div></div>)}
  </div>}

  {tab==="Limite" && <div style={{border:'2px solid #000',borderRadius:10,padding:10,marginTop:10}}>
   <b>Limite global modifiable - Vendeurs chwazi</b>
   <div>Bolet <input type="number" value={db.limits.global.bolet} onChange={e=>up((d:any)=>d.limits.global.bolet=parseInt(e.target.value)||0)} style={{width:'100%',padding:12,border:'2px solid #000',borderRadius:8}}/></div>
   <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6,marginTop:6}}><div>Maryaj<input type="number" value={db.limits.global.maryaj} onChange={e=>up((d:any)=>d.limits.global.maryaj=parseInt(e.target.value)||0)} style={{width:'100%',padding:12,border:'2px solid #000',borderRadius:8}}/></div><div>Loto3<input type="number" value={db.limits.global.loto3} onChange={e=>up((d:any)=>d.limits.global.loto3=parseInt(e.target.value)||0)} style={{width:'100%',padding:12,border:'2px solid #000',borderRadius:8}}/></div></div>
  </div>}

  {tab==="Fermeture" && <div style={{border:'2px solid #000',borderRadius:10,padding:10,marginTop:10}}><b>L'heure fermeture modifiable</b>{TIRAGES.map(t=><div key={t} style={{display:'flex',justifyContent:'space-between',padding:6,borderBottom:'1px solid #ccc'}}><span>{t}</span><input type="time" value={db.fermetures[t]||"12:00"} onChange={e=>up((d:any)=>d.fermetures[t]=e.target.value)} style={{padding:6,border:'2px solid #000',borderRadius:6}}/></div>)}</div>}

  {tab==="Prix" && <div style={{border:'2px solid #000',borderRadius:10,padding:10,marginTop:10}}><b>Prix paiement modifiable</b><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:6,marginTop:8}}><div>1er 50<input value={db.prix.global.lot1} onChange={e=>up((d:any)=>d.prix.global.lot1=parseInt(e.target.value)||0)} style={{width:'100%',padding:10,border:'2px solid #000',borderRadius:8}}/></div><div>2e 20<input value={db.prix.global.lot2} onChange={e=>up((d:any)=>d.prix.global.lot2=parseInt(e.target.value)||0)} style={{width:'100%',padding:10,border:'2px solid #000',borderRadius:8}}/></div><div>3e 10<input value={db.prix.global.lot3} onChange={e=>up((d:any)=>d.prix.global.lot3=parseInt(e.target.value)||0)} style={{width:'100%',padding:10,border:'2px solid #000',borderRadius:8}}/></div><div>M1 1000<input value={db.prix.global.m1} onChange={e=>up((d:any)=>d.prix.global.m1=parseInt(e.target.value)||0)} style={{width:'100%',padding:10,border:'2px solid #000',borderRadius:8}}/></div><div>M2 1000<input value={db.prix.global.m2} onChange={e=>up((d:any)=>d.prix.global.m2=parseInt(e.target.value)||0)} style={{width:'100%',padding:10,border:'2px solid #000',borderRadius:8}}/></div><div>M3 1000<input value={db.prix.global.m3} onChange={e=>up((d:any)=>d.prix.global.m3=parseInt(e.target.value)||0)} style={{width:'100%',padding:10,border:'2px solid #000',borderRadius:8}}/></div></div></div>}

  {tab==="Résultats" && <div style={{border:'2px solid #000',borderRadius:10,padding:10,marginTop:10}}><b>Rezilta (chwazi Tiraj) - 9 kaz</b><select value={selTiraj} onChange={e=>setSelTiraj(e.target.value)} style={{width:'100%',padding:12,border:'2px solid #000',borderRadius:8,marginTop:8}}>{TIRAGES.map(t=><option key={t}>{t}</option>)}</select><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8,marginTop:10}}>{["p1:1er","p2:2e","p3:3e","m1:M1","m2:M2","m3:M3","l3:L3","l4:L4","l5:L5"].map(k=>{ const [f,l]=k.split(':'); return <div key={f}>{l}<input value={db.resultats[selTiraj]?.[f]||""} onChange={e=>up((d:any)=>{ if(!d.resultats[selTiraj]) d.resultats[selTiraj]={}; d.resultats[selTiraj][f]=e.target.value })} style={{width:'100%',padding:14,border:'3px solid #000',borderRadius:8,fontWeight:900,textAlign:'center'}}/></div>})}</div><div style={{marginTop:10,background:'#f5f5f5',border:'1px solid #000',borderRadius:8,padding:8,fontSize:10}}>{Object.entries(db.resultats).map(([t,r]:any)=><div key={t}>{t}: {r.p1} {r.p2} {r.p3} | {r.m1} {r.m2} {r.m3} | {r.l3} {r.l4} {r.l5}</div>)}</div></div>}

  {tab==="Rapport" && <div style={{border:'2px solid #000',borderRadius:10,padding:10,marginTop:10}}>Rapport - Du Au - Vendeurs tous - Tirages tous - Vente: {db.tickets.reduce((s:any,f:any)=>s+f.miz,0)} HTG - chak tiraj kalkile separeman</div>}
  {tab==="Entête" && <div style={{border:'2px solid #000',borderRadius:10,padding:10,marginTop:10}}><b>Entête</b><input value={db.antet.nom} onChange={e=>up((d:any)=>d.antet.nom=e.target.value)} style={{width:'100%',padding:12,border:'2px solid #000',borderRadius:8,marginTop:6}}/><input value={db.proprios[0]?.modpas||""} onChange={e=>up((d:any)=>d.proprios[0].modpas=e.target.value)} placeholder="Modpas proprio modifiable" style={{width:'100%',padding:12,border:'2px solid #000',borderRadius:8,marginTop:6}}/></div>}
  {tab==="Param" && <div style={{border:'2px solid #000',borderRadius:10,padding:10,marginTop:10}}><b>Paramètres - Horaires Lundi-Dimanche + Bloke boul + Bloke vandè</b><div style={{marginTop:8}}><input placeholder="Bloke boul 00-99" id="bbloke" style={{width:'70%',padding:10,border:'2px solid #000',borderRadius:8}}/><button onClick={()=>{ const v=(document.getElementById('bbloke') as any).value; if(v) up((d:any)=>{ if(!d.boulBloke.includes(v)) d.boulBloke.push(v); }); }} style={{width:'28%',marginLeft:'2%',padding:10,background:'#000',color:'#fff',borderRadius:8}}>Bloke</button></div><div style={{marginTop:6}}>{db.boulBloke.map((b:any)=><span key={b} style={{background:'#000',color:'#fff',padding:'4px 8px',borderRadius:8,margin:2,display:'inline-block'}} onClick={()=>up((d:any)=>d.boulBloke=d.boulBloke.filter((x:any)=>x!==b))}>{b} X</span>)}</div></div>}

  <button onClick={()=>{ saveDB(db); alert("✅ ANREJISTRE V4 - Pa bloke ankò!"); }} style={{width:'100%',padding:16,background:'#000',color:'#fff',borderRadius:12,fontWeight:900,marginTop:12}}>💾 ANREJISTRE</button>
 </div>);
}
