"use client";
import { useState, useEffect } from "react";
import { loadDB, saveDB, GlobalDB } from "../lib/db";
const TIRAGES = ["GA midi","FL midi","NY midi","Real","GA soir","FL soir","NY soir","Real 12h45","Primera dia","Suerte dia","Lote Dom","Ganamas","Suerte noche","Primera noche","Loteka","Nacional noche","Leidsa","Anguila 10h","Anguila 18h"];
export default function Proprio(){
  const [db,setDb]=useState<GlobalDB | null>(null); const [selTirajRez,setSelTirajRez]=useState(""); const [selVandeLimit,setSelVandeLimit]=useState(""); const [selVandePri,setSelVandePri]=useState(""); const [newV,setNewV]=useState({nom:"",modpas:"",pou:"20"});
  useEffect(()=>{ setDb(loadDB()); },[]);
  if(!db) return <div>Loading...</div>;
  const update=(fn:(d:GlobalDB)=>void)=>{ const nd={...db}; fn(nd); setDb(nd); saveDB(nd); };
  return (<div style={{maxWidth:'520px',margin:'0 auto',padding:'10px',background:'#fff',color:'#000'}}>
    <h2 style={{fontWeight:'900',textAlign:'center',border:'3px solid #000',padding:'10px',borderRadius:'12px'}}>PROPRIO - MENM BAZ</h2>
    <div style={{border:'2px solid #000',borderRadius:'12px',padding:'10px',marginTop:'10px'}}><b>Rezilta (chwazi Tiraj)</b><select value={selTirajRez} onChange={e=>setSelTirajRez(e.target.value)} style={{width:'100%',padding:'12px',border:'2px solid #000',borderRadius:'8px',marginTop:'6px'}}><option value="">-- Chwazi Tiraj --</option>{TIRAGES.map(t=><option key={t}>{t}</option>)}</select>{selTirajRez && <div style={{display:'flex',gap:'6px',marginTop:'8px'}}><input value={db.resultats[selTirajRez]||""} onChange={e=>update(d=>d.resultats[selTirajRez]=e.target.value)} placeholder={`Rezilta ${selTirajRez}`} style={{flex:1,padding:'12px',border:'2px solid #000',borderRadius:'8px',fontWeight:'900'}}/><button onClick={()=>saveDB(db)} style={{background:'#000',color:'#fff',padding:'10px',borderRadius:'8px'}}>OK</button></div>}</div>
    <div style={{border:'2px solid #000',borderRadius:'12px',padding:'10px',marginTop:'10px'}}><b>Limit global/proprio/vandè: chwazi pou ki vandè</b><div style={{display:'flex',gap:'6px',marginTop:'6px'}}><input type="number" value={db.limits.global} onChange={e=>update(d=>d.limits.global=parseInt(e.target.value)||0)} style={{flex:1,padding:'12px',border:'2px solid #000',borderRadius:'8px'}}/><select value={selVandeLimit} onChange={e=>setSelVandeLimit(e.target.value)} style={{flex:1,padding:'12px',border:'2px solid #000',borderRadius:'8px'}}><option value="">Chwazi vandè</option>{db.vendeurs.map(v=><option key={v.id}>{v.nom}</option>)}</select></div>{selVandeLimit && <div style={{display:'flex',gap:'6px',marginTop:'6px'}}><input type="number" value={db.limits.vendeur[selVandeLimit]||""} onChange={e=>update(d=>d.limits.vendeur[selVandeLimit]=parseInt(e.target.value)||0)} placeholder={`Limit pou ${selVandeLimit}`} style={{flex:1,padding:'10px',border:'2px solid #000',borderRadius:'8px'}}/><button onClick={()=>saveDB(db)} style={{background:'#0d7a3e',color:'#fff',padding:'10px',borderRadius:'8px'}}>OK</button></div>}</div>
    <div style={{border:'2px solid #000',borderRadius:'12px',padding:'10px',marginTop:'10px'}}><b>Pri Peye global/proprio/vandè: Chwazi pou ki vandè</b><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:'6px',marginTop:'6px'}}><div>Global Bolet <input type="number" value={db.prix.global.bolet} onChange={e=>update(d=>d.prix.global.bolet=parseInt(e.target.value)||0)} style={{width:'100%',padding:'10px',border:'2px solid #000',borderRadius:'8px'}}/></div><div>Maryaj <input type="number" value={db.prix.global.maryaj} onChange={e=>update(d=>d.prix.global.maryaj=parseInt(e.target.value)||0)} style={{width:'100%',padding:'10px',border:'2px solid #000',borderRadius:'8px'}}/></div><div>Loto3 <input type="number" value={db.prix.global.loto3} onChange={e=>update(d=>d.prix.global.loto3=parseInt(e.target.value)||0)} style={{width:'100%',padding:'10px',border:'2px solid #000',borderRadius:'8px'}}/></div></div><select value={selVandePri} onChange={e=>setSelVandePri(e.target.value)} style={{width:'100%',padding:'12px',border:'2px solid #000',borderRadius:'8px',marginTop:'8px'}}><option value="">-- Chwazi pou ki vandè --</option>{db.vendeurs.map(v=><option key={v.id}>{v.nom}</option>)}</select>{selVandePri && <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:'6px',marginTop:'6px'}}><input type="number" placeholder="Bolet" value={db.prix.vendeur[selVandePri]?.bolet||""} onChange={e=>update(d=>{if(!d.prix.vendeur[selVandePri]) d.prix.vendeur[selVandePri]={}; d.prix.vendeur[selVandePri].bolet=parseInt(e.target.value)||0})} style={{padding:'10px',border:'2px solid #000',borderRadius:'8px'}}/><input type="number" placeholder="Maryaj" value={db.prix.vendeur[selVandePri]?.maryaj||""} onChange={e=>update(d=>{if(!d.prix.vendeur[selVandePri]) d.prix.vendeur[selVandePri]={}; d.prix.vendeur[selVandePri].maryaj=parseInt(e.target.value)||0})} style={{padding:'10px',border:'2px solid #000',borderRadius:'8px'}}/><input type="number" placeholder="Loto3" value={db.prix.vendeur[selVandePri]?.loto3||""} onChange={e=>update(d=>{if(!d.prix.vendeur[selVandePri]) d.prix.vendeur[selVandePri]={}; d.prix.vendeur[selVandePri].loto3=parseInt(e.target.value)||0})} style={{padding:'10px',border:'2px solid #000',borderRadius:'8px'}}/></div>}</div>
    <button onClick={()=>{saveDB(db); alert("✅ Anrejistre nan menm baz!");}} style={{width:'100%',padding:'18px',background:'#000',color:'#fff',borderRadius:'12px',fontWeight:'900',marginTop:'14px'}}>💾 ANREJISTRE</button>
  </div>);
}
