"use client";
import { useState, useEffect } from "react";
export default function Proprio(){
const [auth,setAuth]=useState(false);const [pass,setPass]=useState("");const [proprio,setProprio]=useState<any>(null);const [vendeurs,setVendeurs]=useState<any[]>([]);const [fiches,setFiches]=useState<any[]>([]);const [tab,setTab]=useState("vendeur");
useEffect(()=>{setFiches(JSON.parse(localStorage.getItem("cd_fiches")||"[]"));const c=localStorage.getItem("cd_current_proprio");if(c){setAuth(true);setProprio(JSON.parse(c));const allV=JSON.parse(localStorage.getItem("cd_vendeurs")||"[]");setVendeurs(allV.filter((v:any)=>v.proprioId===JSON.parse(c).id));}},[]);
const login=()=>{const prs=JSON.parse(localStorage.getItem("cd_proprios")||"[]");const f=prs.find((p:any)=>p.password===pass);if(f){setProprio(f);setAuth(true);localStorage.setItem("cd_current_proprio",JSON.stringify(f));const allV=JSON.parse(localStorage.getItem("cd_vendeurs")||"[]");setVendeurs(allV.filter((v:any)=>v.proprioId===f.id));setFiches(JSON.parse(localStorage.getItem("cd_fiches")||"[]"));}else alert("Modpas pa bon - Mande Super Admin!");};
const toggleBlock=(id:string)=>{const all=JSON.parse(localStorage.getItem("cd_vendeurs")||"[]");const nv=all.map((v:any)=>v.id===id?{...v,blocked:!v.blocked}:v);localStorage.setItem("cd_vendeurs",JSON.stringify(nv));setVendeurs(nv.filter((v:any)=>v.proprioId===proprio.id));};
if(!auth)return(<div style={{minHeight:"100vh",background:"white",display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{background:"#fef2f2",padding:24,borderRadius:16,border:"2px solid black",width:360}}><h1 style={{color:"#dc2626",fontWeight:900,textAlign:"center"}}>PROPRIO - KONTWÒL</h1><p style={{textAlign:"center",fontSize:12,marginTop:6,color:"#1d4ed8"}}>Sèl Super ka kreye ou</p><input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="Modpas Proprio" style={{width:"100%",height:50,border:"2px solid black",borderRadius:10,textAlign:"center",marginTop:12}}/><button onClick={login} style={{width:"100%",background:"#dc2626",color:"white",fontWeight:900,padding:14,borderRadius:10,marginTop:10}}>ANTRE</button></div></div>);
const fichesProprio=fiches.filter((f:any)=>vendeurs.some((v:any)=>v.nom===f.vendeur));const total=fichesProprio.reduce((s:any,f:any)=>s+f.total,0);
return(<div style={{minHeight:"100vh",background:"white",padding:10,fontFamily:"sans-serif"}}>
<h1 style={{fontWeight:900,textAlign:"center",fontSize:20}}><span style={{color:"#dc2626"}}>PROPRIO</span> <span style={{color:"#1d4ed8"}}>{proprio?.nom}</span></h1>
<div style={{display:"flex",gap:6,marginTop:12}}><button onClick={()=>setTab("vendeur")} style={{flex:1,background:tab==="vendeur"?"#facc15":"#eee",fontWeight:900,padding:10,borderRadius:10,border:"1px solid black"}}>VANDEUR ({vendeurs.length})</button><button onClick={()=>setTab("rapport")} style={{flex:1,background:tab==="rapport"?"#4ade80":"#eee",fontWeight:900,padding:10,borderRadius:10,border:"1px solid black"}}>RAPPORT</button></div>
<div style={{background:"#fef9c3",border:"2px solid black",borderRadius:12,padding:12,textAlign:"center",marginTop:10}}><span style={{color:"#1d4ed8"}}>Vandè:</span> <b style={{color:"#dc2626"}}>{vendeurs.length}</b> | <span style={{color:"#15803d"}}>Vente:</span> <b>{total}G</b></div>
{tab==="vendeur"&&(<div style={{marginTop:15}}>{vendeurs.map((v:any)=><div key={v.id} style={{border:"2px solid black",borderRadius:12,padding:10,marginTop:8,background:v.blocked?"#fecaca":"#fefce8"}}><div style={{display:"flex",justifyContent:"space-between"}}><div><b style={{color:"#ca8a04"}}>{v.nom}</b><br/><span style={{fontSize:11,color:"#1d4ed8"}}>Modpas: {v.password}</span><br/><span style={{fontSize:11,color:v.blocked?"#dc2626":"#15803d"}}>{v.blocked?"🔴 BLOKE":"🟢 AKTIF"}</span></div><button onClick={()=>toggleBlock(v.id)} style={{background:v.blocked?"#15803d":"#dc2626",color:"white",fontWeight:900,padding:"6px 12px",borderRadius:8,border:"none",height:35}}>{v.blocked?"DEBLOKE":"BLOKE"}</button></div><div style={{marginTop:6,fontSize:11}}>Fich: {fiches.filter((f:any)=>f.vendeur===v.nom).length} | Vente: {fiches.filter((f:any)=>f.vendeur===v.nom).reduce((s:any,f:any)=>s+f.total,0)}G</div></div>)}{vendeurs.length===0&&<div style={{textAlign:"center",marginTop:20,color:"#dc2626",fontWeight:700}}>Super Admin poko kreye vandè pou ou!</div>}</div>)}
{tab==="rapport"&&(<div style={{marginTop:15}}>{fichesProprio.slice(0,20).map((f:any)=><div key={f.id} style={{border:"1px solid black",borderRadius:8,padding:8,marginTop:6,fontSize:12}}><b style={{color:"#1d4ed8"}}>{f.id}</b> - <span style={{color:"#ca8a04"}}>{f.vendeur}</span> - <b style={{color:"#15803d"}}>{f.total}G</b><br/>{new Date(f.date).toLocaleString()}</div>)}</div>)}
<div style={{textAlign:"center",marginTop:20}}><button onClick={()=>{localStorage.removeItem("cd_current_proprio");setAuth(false);}} style={{background:"black",color:"white",padding:"8px 20px",borderRadius:8,fontWeight:900}}>DEKONEKTE</button></div>
</div>);
}
