"use client";
import { useState, useEffect } from "react";
import { loadDB, saveDB, GlobalDB } from "../lib/db";
const TIRAGES = ["GA midi","FL midi","NY midi","Real","GA soir","FL soir","NY soir","Real 12h45","Primera dia","Suerte dia","Lote Dom","Ganamas","Suerte noche","Primera noche","Loteka","Nacional noche","Leidsa","Anguila 10h","Anguila 18h"];
export default function Sup(){
  const [db,setDb]=useState<GlobalDB | null>(null); const [tab,setTab]=useState("Rezilta"); const [selTiraj,setSelTiraj]=useState(""); const [selProprio,setSelProprio]=useState(""); const [selVande,setSelVande]=useState("");
  useEffect(()=>{ setDb(loadDB()); },[]); if(!db) return <div>Loading baz...</div>;
  const up=(fn:(d:GlobalDB)=>void)=>{ const nd={...db}; fn(nd); setDb(nd); saveDB(nd); };
  return (<div style={{background:'#000',minHeight:'100vh',color:'#fff',padding:'10px'}}><h1 style={{color:'red',textAlign:'center',fontWeight:'900',fontSize:'26px'}}>🔴 SUPER-ADMIN C&D</h1><div style={{display:'flex',gap:'8px',overflowX:'auto',paddingBottom:'10px'}}>{["Rezilta","Limit","Pri Peye","Lè Fèmen","Bloke"].map(t=><button key={t} onClick={()=>setTab(t)} style={{padding:'12px 20px',borderRadius:'24px',border:'none',fontWeight:'900',background:tab===t?'red':'#333',color:'#fff',whiteSpace:'nowrap'}}>{t}</button>)}</div>
  {tab==="Rezilta" && <div style={{background:'#1a1a1a',borderRadius:'16px',padding:'14px',marginTop:'10px'}}><b>Rezilta (chwazi Tiraj)</b><select value={selTiraj} onChange={e=>setSelTiraj(e.target.value)} style={{width:'100%',padding:'14px',borderRadius:'12px',background:'#333',color:'#fff',marginTop:'8px',border:'1px solid #555'}}><option value="">-- Chwazi Tiraj --</option>{TIRAGES.map(t=><option key={t}>{t}</option>)}</select>{selTiraj && <><input value={db.resultats[selTiraj]||""} onChange={e=>up(d=>d.resultats[selTiraj]=e.target.value)} placeholder={`Rezilta ${selTiraj} ex: 12 45 78`} style={{width:'100%',padding:'16px',borderRadius:'12px',background:'#000',color:'#fff',marginTop:'10px',fontWeight:'900',border:'2px solid #555'}}/><button onClick={()=>{saveDB(db); alert("✅ Rezilta "+selTiraj+" : "+db.resultats[selTiraj]);}} style={{width:'100%',marginTop:'10px',padding:'16px',background:'#0d7a3e',color:'#fff',borderRadius:'12px',fontWeight:'900',border:'none'}}>ANREJISTRE REZILTA</button></>}{Object.entries(db.resultats).map(([k,v])=><div key={k} style={{padding:'8px',borderBottom:'1px solid #333',marginTop:'6px'}}>{k}: <span style={{color:'#0f0',fontWeight:'900'}}>{v}</span></div>)}</div>}
  {tab==="Limit" && <div style={{background:'#1a1a1a',borderRadius:'16px',padding:'14px',marginTop:'10px'}}><b>Limit global/proprio/vandè : chwazi pou ki proprio (pou ki vandè)</b><div style={{marginTop:'10px'}}><label>Limit Global</label><input type="number" value={db.limits.global} onChange={e=>up(d=>d.limits.global=parseInt(e.target.value)||0)} style={{width:'100%',padding:'14px',borderRadius:'12px',background:'#000',color:'#fff',marginTop:'4px'}}/></div><div style={{marginTop:'12px'}}><label>Chwazi pou ki proprio</label><select value={selProprio} onChange={e=>{setSelProprio(e.target.value); setSelVande("")}} style={{width:'100%',padding:'14px',borderRadius:'12px',background:'#333',color:'#fff',marginTop:'4px'}}><option value="">-- Proprio --</option>{db.proprios.map(p=><option key={p.id} value={p.nom}>{p.nom}</option>)}</select>{selProprio && <input type="number" value={db.limits.proprio[selProprio]||""} onChange={e=>up(d=>d.limits.proprio[selProprio]=parseInt(e.target.value)||0)} placeholder={`Limit pou ${selProprio}`} style={{width:'100%',padding:'14px',borderRadius:'12px',background:'#000',color:'#fff',marginTop:'8px'}}/>}</div><div style={{marginTop:'12px'}}><label>Chwazi pou ki vandè</label><select value={selVande} onChange={e=>setSelVande(e.target.value)} style={{width:'100%',padding:'14px',borderRadius:'12px',background:'#333',color:'#fff',marginTop:'4px'}}><option value="">-- Vandè --</option>{db.vendeurs.map(v=><option key={v.id} value={v.nom}>{v.nom}</option>)}</select>{selVande && <input type="number" value={db.limits.vendeur[selVande]||""} onChange={e=>up(d=>d.limits.vendeur[selVande]=parseInt(e.target.value)||0)} placeholder={`Limit pou vandè ${selVande}`} style={{width:'100%',padding:'14px',borderRadius:'12px',background:'#000',color:'#fff',marginTop:'8px'}}/>}</div></div>}
  {tab==="Pri Peye" && <div style={{background:'#1a1a1a',borderRadius:'16px',padding:'14px',marginTop:'10px'}}><b>Pri Peye global/proprio/vandè : Chwazi pou ki proprio (pou Ki vandè)</b><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:'8px',marginTop:'10px'}}><div>Global Bolet <input type="number" value={db.prix.global.bolet} onChange={e=>up(d=>d.prix.global.bolet=parseInt(e.target.value)||0)} style={{width:'100%',padding:'10px',borderRadius:'10px',background:'#000',color:'#fff'}}/></div><div>Maryaj <input type="number" value={db.prix.global.maryaj} onChange={e=>up(d=>d.prix.global.maryaj=parseInt(e.target.value)||0)} style={{width:'100%',padding:'10px',borderRadius:'10px',background:'#000',color:'#fff'}}/></div><div>Loto3 <input type="number" value={db.prix.global.loto3} onChange={e=>up(d=>d.prix.global.loto3=parseInt(e.target.value)||0)} style={{width:'100%',padding:'10px',borderRadius:'10px',background:'#000',color:'#fff'}}/></div></div><div style={{marginTop:'12px'}}><select value={selProprio} onChange={e=>setSelProprio(e.target.value)} style={{width:'100%',padding:'14px',borderRadius:'12px',background:'#333',color:'#fff'}}><option value="">-- Chwazi pou ki proprio --</option>{db.proprios.map(p=><option key={p.id} value={p.nom}>{p.nom}</option>)}</select></div><div style={{marginTop:'10px'}}><select value={selVande} onChange={e=>setSelVande(e.target.value)} style={{width:'100%',padding:'14px',borderRadius:'12px',background:'#333',color:'#fff'}}><option value="">-- Pou ki vandè --</option>{db.vendeurs.map(v=><option key={v.id} value={v.nom}>{v.nom}</option>)}</select>{selVande && <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:'6px',marginTop:'8px'}}><input type="number" placeholder="Bolet" value={db.prix.vendeur[selVande]?.bolet||""} onChange={e=>up(d=>{if(!d.prix.vendeur[selVande]) d.prix.vendeur[selVande]={}; d.prix.vendeur[selVande].bolet=parseInt(e.target.value)||0})} style={{padding:'12px',borderRadius:'10px',background:'#000',color:'#fff'}}/><input type="number" placeholder="Maryaj" value={db.prix.vendeur[selVande]?.maryaj||""} onChange={e=>up(d=>{if(!d.prix.vendeur[selVande]) d.prix.vendeur[selVande]={}; d.prix.vendeur[selVande].maryaj=parseInt(e.target.value)||0})} style={{padding:'12px',borderRadius:'10px',background:'#000',color:'#fff'}}/><input type="number" placeholder="Loto3" value={db.prix.vendeur[selVande]?.loto3||""} onChange={e=>up(d=>{if(!d.prix.vendeur[selVande]) d.prix.vendeur[selVande]={}; d.prix.vendeur[selVande].loto3=parseInt(e.target.value)||0})} style={{padding:'12px',borderRadius:'10px',background:'#000',color:'#fff'}}/></div>}</div></div>}
  {tab==="Lè Fèmen" && <div style={{background:'#1a1a1a',borderRadius:'16px',padding:'14px',marginTop:'10px'}}><b>Lè Fèmen - chwazi tiraj</b>{TIRAGES.map(t=><div key={t} style={{display:'flex',justifyContent:'space-between',padding:'12px',borderBottom:'1px solid #333'}}><span>{t}</span><input type="time" value={db.fermetures[t]||""} onChange={e=>up(d=>d.fermetures[t]=e.target.value)} style={{background:'#000',color:'#fff',border:'1px solid #555',borderRadius:'8px',padding:'6px'}}/></div>)}</div>}
  <div style={{marginTop:'14px'}}>{db.proprios.map(p=><div key={p.id} style={{background:'#1a1a1a',border:'1px solid #333',borderRadius:'14px',padding:'14px',display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'10px'}}><div><div style={{fontWeight:'900',fontSize:'18px'}}>{p.nom}</div><div style={{fontSize:'12px',color:'#aaa'}}>{p.tel} | {p.vendeur} vandè | <span style={{color:p.statut==="Aktif"?"#0f0":"red"}}>{p.statut}</span></div></div><button onClick={()=>up(d=>{const pr=d.proprios.find(x=>x.id===p.id); if(pr) pr.statut=pr.statut==="Aktif"?"Bloke":"Aktif"})} style={{padding:'10px 18px',borderRadius:'12px',border:'none',fontWeight:'900',background:p.statut==="Aktif"?"red":"#0d7a3e",color:'#fff'}}>{p.statut==="Aktif"?"BLOKE":"DEBLOKE"}</button></div>)}</div>
  </div>);
}
