"use client";
import { useState, useEffect } from "react";
import { loadDB, saveDB, GlobalDB } from "../lib/db";
const TIRAGES = ["GA midi","FL midi","NY midi","Real","GA soir","FL soir","NY soir","Real 12h45","Primera dia","Suerte dia","Lote Dom","Ganamas","Suerte noche","Primera noche","Loteka","Nacional noche","Leidsa","Anguila 10h","Anguila 18h"];
export default function Sup(){
  const [db,setDb]=useState<GlobalDB | null>(null); const [tab,setTab]=useState("Rezilta"); const [selTiraj,setSelTiraj]=useState(""); const [selProprio,setSelProprio]=useState(""); const [selVande,setSelVande]=useState("");
  useEffect(()=>{ setDb(loadDB()); },[]); if(!db) return <div>Loading...</div>;
  const update=(fn:(d:GlobalDB)=>void)=>{ const nd={...db}; fn(nd); setDb(nd); saveDB(nd); };
  return (<div style={{background:'#000',minHeight:'100vh',color:'#fff',padding:'10px'}}><h1 style={{color:'red',textAlign:'center',fontWeight:'900'}}>🔴 SUPER-ADMIN - MENM BAZ</h1><div style={{display:'flex',gap:'8px',overflowX:'auto'}}>{["Rezilta","Limit","Pri Peye","Lè Fèmen","Bloke"].map(t=><button key={t} onClick={()=>setTab(t)} style={{padding:'12px 20px',borderRadius:'24px',border:'none',fontWeight:'900',background:tab===t?'red':'#333',color:'#fff'}}>{t}</button>)}</div>
  {tab==="Rezilta" && <div style={{background:'#1a1a1a',borderRadius:'16px',padding:'14px',marginTop:'10px'}}><b>Rezilta (chwazi Tiraj)</b><select value={selTiraj} onChange={e=>setSelTiraj(e.target.value)} style={{width:'100%',padding:'14px',borderRadius:'12px',background:'#333',color:'#fff',marginTop:'8px'}}><option value="">-- Chwazi Tiraj --</option>{TIRAGES.map(t=><option key={t}>{t}</option>)}</select>{selTiraj && <><input value={db.resultats[selTiraj]||""} onChange={e=>update(d=>d.resultats[selTiraj]=e.target.value)} placeholder={`Rezilta ${selTiraj}`} style={{width:'100%',padding:'16px',borderRadius:'12px',background:'#000',color:'#fff',marginTop:'10px',fontWeight:'900'}}/><button onClick={()=>{saveDB(db); alert("Rezilta anrejistre!");}} style={{width:'100%',marginTop:'10px',padding:'16px',background:'#0d7a3e',color:'#fff',borderRadius:'12px',fontWeight:'900',border:'none'}}>ANREJISTRE REZILTA</button></>}</div>}
  {tab==="Limit" && <div style={{background:'#1a1a1a',borderRadius:'16px',padding:'14px',marginTop:'10px'}}><b>Limit global/proprio/vandè: chwazi pou ki proprio (pou ki vandè)</b><div style={{marginTop:'10px'}}><label>Global</label><input type="number" value={db.limits.global} onChange={e=>update(d=>d.limits.global=parseInt(e.target.value)||0)} style={{width:'100%',padding:'14px',borderRadius:'12px',background:'#000',color:'#fff',marginTop:'4px'}}/></div><div style={{marginTop:'12px'}}><label>Chwazi pou ki proprio</label><select value={selProprio} onChange={e=>{setSelProprio(e.target.value); setSelVande("")}} style={{width:'100%',padding:'14px',borderRadius:'12px',background:'#333',color:'#fff',marginTop:'4px'}}><option value="">-- Proprio --</option>{db.proprios.map(p=><option key={p.id} value={p.nom}>{p.nom}</option>)}</select></div>{selProprio && <div style={{marginTop:'10px'}}><input type="number" placeholder={`Limit pou ${selProprio}`} value={db.limits.proprio[selProprio]||""} onChange={e=>update(d=>d.limits.proprio[selProprio]=parseInt(e.target.value)||0)} style={{width:'100%',padding:'14px',borderRadius:'12px',background:'#000',color:'#fff'}}/></div>}<div style={{marginTop:'12px'}}><label>Chwazi pou ki vandè</label><select value={selVande} onChange={e=>setSelVande(e.target.value)} style={{width:'100%',padding:'14px',borderRadius:'12px',background:'#333',color:'#fff',marginTop:'4px'}}><option value="">-- Vandè --</option>{db.vendeurs.map(v=><option key={v.id}>{v.nom}</option>)}</select></div>{selVande && <div style={{marginTop:'10px'}}><input type="number" placeholder={`Limit pou vandè ${selVande}`} value={db.limits.vendeur[selVande]||""} onChange={e=>update(d=>d.limits.vendeur[selVande]=parseInt(e.target.value)||0)} style={{width:'100%',padding:'14px',borderRadius:'12px',background:'#000',color:'#fff'}}/></div>}</div>}
  {tab==="Pri Peye" && <div style={{background:'#1a1a1a',borderRadius:'16px',padding:'14px',marginTop:'10px'}}><b>Pri Peye global/proprio/vandè: Chwazi pou ki proprio (pou Ki vandè)</b><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:'8px',marginTop:'10px'}}><div>Global Bolet <input type="number" value={db.prix.global.bolet} onChange={e=>update(d=>d.prix.global.bolet=parseInt(e.target.value)||0)} style={{width:'100%',padding:'10px',borderRadius:'10px',background:'#000',color:'#fff'}}/></div><div>Maryaj <input type="number" value={db.prix.global.maryaj} onChange={e=>update(d=>d.prix.global.maryaj=parseInt(e.target.value)||0)} style={{width:'100%',padding:'10px',borderRadius:'10px',background:'#000',color:'#fff'}}/></div><div>Loto3 <input type="number" value={db.prix.global.loto3} onChange={e=>update(d=>d.prix.global.loto3=parseInt(e.target.value)||0)} style={{width:'100%',padding:'10px',borderRadius:'10px',background:'#000',color:'#fff'}}/></div></div><div style={{marginTop:'12px'}}><select value={selProprio} onChange={e=>setSelProprio(e.target.value)} style={{width:'100%',padding:'14px',borderRadius:'12px',background:'#333',color:'#fff'}}><option value="">-- Chwazi pou ki proprio --</option>{db.proprios.map(p=><option key={p.id}>{p.nom}</option>)}</select></div><div style={{marginTop:'10px'}}><select value={selVande} onChange={e=>setSelVande(e.target.value)} style={{width:'100%',padding:'14px',borderRadius:'12px',background:'#333',color:'#fff'}}><option value="">-- Pou ki vandè --</option>{db.vendeurs.map(v=><option key={v.id}>{v.nom}</option>)}</select></div></div>}
  <div style={{marginTop:'14px'}}>{db.proprios.map(p=><div key={p.id} style={{background:'#1a1a1a',border:'1px solid #333',borderRadius:'14px',padding:'14px',display:'flex',justifyContent:'space-between',marginBottom:'10px'}}><div><div style={{fontWeight:'900'}}>{p.nom}</div><div style={{fontSize:'12px',color:'#aaa'}}>{p.tel} | {p.statut}</div></div><button onClick={()=>update(d=>{const pr=d.proprios.find(x=>x.id===p.id); if(pr) pr.statut=pr.statut==="Aktif"?"Bloke":"Aktif"})} style={{padding:'10px 18px',borderRadius:'12px',border:'none',fontWeight:'900',background:p.statut==="Aktif"?"red":"#0d7a3e",color:'#fff'}}>{p.statut==="Aktif"?"BLOKE":"DEBLOKE"}</button></div>)}</div>
  </div>);
}
