"use client"; import{useState,useEffect}from"react";
const TIR=["GA midi","FL midi","NY midi","GA soir","FL soir","NY soir","Real 12h45","Primera día","Suerte día","Lote Dom","Ganamas","Suerte noche","Primera noche","Loteka","Nacional noche","Leidsa","Anguila 10h","Anguila 9h55","Anguila 18h","Anguila 17h55"];
const DEF_LIM={Borlette:1500,Mariage:100,Loto3:100,Loto4:20,Loto5:5};const DEF_PRIX={lot1:50,lot2:20,lot3:10,m1:1000,m2:1000,m3:1000,loto3:500,loto4:5000,loto5:25000};
const DEF_FERM:any={"GA midi":"12:15","FL midi":"13:15","NY midi":"14:15","GA soir":"18:15","FL soir":"21:15","NY soir":"22:15","Real 12h45":"12:45","Primera día":"11:50","Suerte día":"12:20","Lote Dom":"13:45","Ganamas":"14:15","Suerte noche":"17:50","Primera noche":"19:50","Loteka":"19:45","Nacional noche":"20:50","Leidsa":"20:45","Anguila 10h":"10:00","Anguila 9h55":"09:55","Anguila 18h":"18:00","Anguila 17h55":"17:55"};

export default function SuperAdmin(){
 const[tab,setTab]=useState("PROPRIO");const[props,setProps]=useState<any[]>([]);const[vands,setVands]=useState<any[]>([]);
 const[pNom,setPNom]=useState("");const[pPass,setPPass]=useState("1234");const[vNom,setVNom]=useState("");const[vPass,setVPass]=useState("1234");const[vProp,setVProp]=useState("");const[vSeri,setVSeri]=useState("");
 const[selPropLim,setSelPropLim]=useState("Global");const[selVandLim,setSelVandLim]=useState("Tous");const[lim,setLim]=useState(DEF_LIM);
 const[ferm,setFerm]=useState(DEF_FERM);const[prix,setPrix]=useState(DEF_PRIX);const[selPropPrix,setSelPropPrix]=useState("Global");const[selVandPrix,setSelVandPrix]=useState("Tous");
 const[selTirRes,setSelTirRes]=useState("GA midi");const[res,setRes]=useState<any>({});const[resultats,setResultats]=useState<any[]>([]);
 const[msg,setMsg]=useState("");const[msgProp,setMsgProp]=useState("Global");const[superPass,setSuperPass]=useState("admin123");
 const[logos,setLogos]=useState<any>({});const[entete,setEntete]=useState<any>({logo:"",nom:"C&D VERITE",dat:true,tiraj:true,vande:true,id:true});const[selEntProp,setSelEntProp]=useState("Global");const[footer,setFooter]=useState("Mèsi - Bonne Chance - C&D Verite Lotto - 47561234");

 useEffect(()=>{setProps(JSON.parse(localStorage.getItem("PROPS")||"[]"));setVands(JSON.parse(localStorage.getItem("ALL_VANDS")||"[]"));setResultats(JSON.parse(localStorage.getItem("SUP_RES")||"[]"));setSuperPass(localStorage.getItem("SUP_PASS")||"admin123");setLogos(JSON.parse(localStorage.getItem("LOGOS")||"{}"));setFooter(localStorage.getItem("FOOTER")||footer)},[]);
 const saveProps=(p:any)=>{localStorage.setItem("PROPS",JSON.stringify(p));setProps(p)};const saveVands=(v:any)=>{localStorage.setItem("ALL_VANDS",JSON.stringify(v));setVands(v)};

 const addProprio=()=>{if(!pNom)return;const pr={id:"P"+Date.now(),nom:pNom,kod:"BOSS"+Math.floor(100+Math.random()*900),modpas:pPass,status:"active",msg:""};saveProps([...props,pr]);setPNom("");setPPass("1234");alert("Proprio kreye: "+pr.kod+" / "+pr.modpas)};
 const addVendeur=()=>{if(!vNom||!vProp)return alert("Chwazi proprio");const pr=props.find(x=>x.id===vProp);const v={id:"V"+Date.now(),nom:vNom,username:vNom.toLowerCase().replace(/\s/g,".")+"."+pr.kod.toLowerCase(),modpas:vPass,proprioId:vProp,proprioNom:pr.nom,serial:vSeri||"TERM-"+Math.floor(1000+Math.random()*9000),status:"active"};saveVands([...vands,v]);const pv=JSON.parse(localStorage.getItem("VANDS_"+vProp)||"[]");localStorage.setItem("VANDS_"+vProp,JSON.stringify([...pv,v]));setVNom("");setVPass("1234");setVSeri("");alert("Vandè kreye pou "+pr.nom+": "+v.username+" / "+vPass+" Serial: "+v.serial)};
 const toggleBlock=(id:string)=>{const np=props.map(p=>p.id===id?{...p,status:p.status==="active"?"blocked":"active"}:p);saveProps(np)};const sendMsg=()=>{if(!msg)return;if(msgProp==="Global"){const np=props.map(p=>({...p,msg}));saveProps(np)}else{const np=props.map(p=>p.id===msgProp?{...p,msg}:p);saveProps(np)}alert("Mesaj voye!");setMsg("")};
 const saveRes=()=>{if(!res.r1)return alert("Mete 1er");const r={tirage:selTirRes,...res,date:new Date().toLocaleDateString()};const nr=[r,...resultats.filter((x:any)=>x.tirage!==selTirRes)];setResultats(nr);localStorage.setItem("SUP_RES",JSON.stringify(nr));setRes({});alert("Rezilta "+selTirRes+" OK")};

 return(<div style={{padding:8,maxWidth:600,margin:"0 auto",fontSize:11}}>
  <h2 style={{textAlign:"center"}}>SUPER ADMIN - C&D</h2>
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:4}}>{["PROPRIO","VENDEUR","BLOKE","MESSAGE","RESULTATS","LIMITE","FERMETURE","PRIX","PARAM"].map(t=><button key={t} onClick={()=>setTab(t)} style={{padding:8,border:"2px solid #000",background:tab===t?"#000":"#eee",color:tab===t?"#fff":"#000",fontSize:9,fontWeight:900}}>{t}</button>)}</div>

  {tab==="PROPRIO"&&<div style={{marginTop:10,border:"2px solid #000",padding:10}}><b>a) Proprio: Kreye nouvo proprio - non - modpas - lis vandè</b><input value={pNom} onChange={e=>setPNom(e.target.value)} placeholder="Non proprio ex: Toto" style={{width:"100%",padding:8,border:"2px solid #000",marginTop:6}}/><input value={pPass} onChange={e=>setPPass(e.target.value)} placeholder="Modpas" style={{width:"100%",padding:8,border:"2px solid #000",marginTop:4}}/><button onClick={addProprio} style={{width:"100%",padding:10,background:"#000",color:"#fff",marginTop:6}}>KREYE PROPRIO</button><div style={{marginTop:10}}>{props.map(p=><div key={p.id} style={{border:"1px solid #000",padding:6,marginTop:4}}><b>{p.nom}</b> - {p.kod}/{p.modpas} - Status: {p.status}<br/>Vandè: {vands.filter(v=>v.proprioId===p.id).length} - Lis: {vands.filter(v=>v.proprioId===p.id).map(v=>v.nom).join(", ")}<br/><button onClick={()=>toggleBlock(p.id)} style={{padding:3,background:p.status==="active"?"orange":"green",color:"#fff"}}>{p.status==="active"?"BLOKE":"DEBLOKE"}</button></div>)}</div></div>}

  {tab==="VENDEUR"&&<div style={{marginTop:10,border:"2px solid #000",padding:10}}><b>b) Vendeur: Kreye nouvo vandè - Pou ki proprio - non - modpas - seri Terminal</b><select value={vProp} onChange={e=>setVProp(e.target.value)} style={{width:"100%",padding:8,border:"2px solid #000",marginTop:6}}><option value="">Pou ki proprio?</option>{props.map(p=><option key={p.id} value={p.id}>{p.nom} - {p.kod}</option>)}</select><input value={vNom} onChange={e=>setVNom(e.target.value)} placeholder="Non vandè" style={{width:"100%",padding:8,border:"2px solid #000",marginTop:4}}/><input value={vPass} onChange={e=>setVPass(e.target.value)} placeholder="Modpas" style={{width:"100%",padding:8,border:"2px solid #000",marginTop:4}}/><input value={vSeri} onChange={e=>setVSeri(e.target.value)} placeholder="Nimewo Seri Terminal ex: TERM-1234" style={{width:"100%",padding:8,border:"2px solid #000",marginTop:4}}/><button onClick={addVendeur} style={{width:"100%",padding:10,background:"#000",color:"#fff",marginTop:6}}>KREYE VANDÈ</button><div style={{marginTop:10}}>{vands.map(v=><div key={v.id} style={{borderBottom:"1px solid #000",padding:4}}> {v.nom} | {v.proprioNom} | User: <b>{v.username}</b> / {v.modpas} | Seri: {v.serial}</div>)}</div></div>}

  {tab==="BLOKE"&&<div style={{marginTop:10,border:"2px solid #000",padding:10}}><b>Bloke - Debloke Kont Proprio</b>{props.map(p=><div key={p.id} style={{border:"1px solid #000",padding:8,marginTop:5,background:p.status==="blocked"?"#ffcccc":"#ccffcc"}}><b>{p.nom}</b> - {p.kod} - {p.status}<button onClick={()=>toggleBlock(p.id)} style={{float:"right",padding:5,background:p.status==="active"?"red":"green",color:"#fff"}}>{p.status==="active"?"BLOKE KONT LA":"DEBLOKE"}</button><br/>Vandè: {vands.filter(v=>v.proprioId===p.id).length}</div>)}</div>}

  {tab==="MESSAGE"&&<div style={{marginTop:10,border:"2px solid #000",padding:10}}><b>Mesaj pou avèti proprio yo avan kont yo bloke</b><select value={msgProp} onChange={e=>setMsgProp(e.target.value)} style={{width:"100%",padding:8,border:"1px solid #000",marginTop:6}}><option value="Global">Tout proprio</option>{props.map(p=><option key={p.id} value={p.id}>{p.nom}</option>)}</select><textarea value={msg} onChange={e=>setMsg(e.target.value)} placeholder="Ex: Kont ou ap bloke demen si ou pa peye 5000 HTG - Tanpri peye" style={{width:"100%",padding:8,border:"2px solid #000",marginTop:6,height:80}}></textarea><button onClick={sendMsg} style={{width:"100%",padding:10,background:"#ff8800",color:"#fff",marginTop:6}}>VOYE MESAJ AVÈTISMAN</button><div style={{marginTop:10}}>{props.filter(p=>p.msg).map(p=><div key={p.id} style={{border:"1px solid orange",padding:5,marginTop:4}}>Pou {p.nom}: {p.msg}</div>)}</div></div>}

  {tab==="RESULTATS"&&<div style={{marginTop:10,border:"2px solid #000",padding:8}}><b>Résultats 9 cases</b><select value={selTirRes} onChange={e=>setSelTirRes(e.target.value)} style={{width:"100%",padding:6,border:"2px solid #000",marginTop:4}}>{TIR.map(t=><option key={t}>{t}</option>)}</select><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr 1fr",gap:4,marginTop:8}}>{["r1 1er","r2 2e","r3 3e","m1 M1","m2 M2","m3 M3","l3 L3","l4 L4","l5 L5"].map(k=>{const [f,l]=k.split(" ");return<div key={f}><span>{l}</span><input value={res[f]||""} onChange={e=>setRes({...res,[f]:e.target.value})} style={{width:"100%",padding:10,border:"2px solid #000",textAlign:"center",fontSize:16}}/></div>})}</div><button onClick={saveRes} style={{width:"100%",padding:10,background:"#000",color:"#fff",marginTop:8}}>ANREJISTRE</button><div style={{marginTop:10,overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:9}}><tr style={{background:"#000",color:"#fff"}}><td>Tir</td><td>1e</td><td>2e</td><td>3e</td><td>M1</td><td>M2</td><td>M3</td><td>L3</td><td>L4</td><td>L5</td></tr>{resultats.map((r:any,i:number)=><tr key={i} style={{borderBottom:"1px solid #000"}}><td>{r.tirage.slice(0,6)}</td><td>{r.r1}</td><td>{r.r2}</td><td>{r.r3}</td><td>{r.m1}</td><td>{r.m2}</td><td>{r.m3}</td><td>{r.l3}</td><td>{r.l4}</td><td>{r.l5}</td></tr>)}</table></div></div>}

  {tab==="LIMITE"&&<div style={{marginTop:10,border:"2px solid #000",padding:8}}><b>Limite Mise Global / Par proprio / vendeur (modifiable)</b><div style={{display:"flex",gap:4,marginTop:6}}><select value={selPropLim} onChange={e=>setSelPropLim(e.target.value)} style={{flex:1,padding:5,border:"1px solid #000"}}><option>Global</option>{props.map(p=><option key={p.id}>{p.nom}</option>)}</select><select value={selVandLim} onChange={e=>setSelVandLim(e.target.value)} style={{flex:1,padding:5,border:"1px solid #000"}}><option>Tous</option>{vands.map(v=><option key={v.id}>{v.nom}</option>)}</select></div>{Object.keys(DEF_LIM).map(k=><div key={k} style={{display:"flex",justifyContent:"space-between",marginTop:6,borderBottom:"1px solid #ccc"}}><span>{k}</span><input type="number" value={lim[k]} onChange={e=>setLim({...lim,[k]:parseInt(e.target.value)||0})} style={{width:70,padding:4,border:"2px solid #000"}}/></div>)}<div style={{fontSize:9,marginTop:5}}>Borlettes 1500 - Mariage 100 - Loto3 100 - Loto4 20 - Loto5 5</div></div>}

  {tab==="FERMETURE"&&<div style={{marginTop:10,border:"2px solid #000",padding:8}}><b>L'heure fermeture modifiable</b>{Object.keys(DEF_FERM).map(k=><div key={k} style={{display:"flex",justifyContent:"space-between",marginTop:3,borderBottom:"1px solid #eee"}}><span>{k}</span><input type="time" value={ferm[k]} onChange={e=>setFerm({...ferm,[k]:e.target.value})} style={{padding:3,border:"1px solid #000"}}/></div>)}</div>}

  {tab==="PRIX"&&<div style={{marginTop:10,border:"2px solid #000",padding:8}}><b>Prix paiement Global / Par proprio / vendeur (modifiable)</b><div style={{display:"flex",gap:4,marginTop:6}}><select value={selPropPrix} onChange={e=>setSelPropPrix(e.target.value)} style={{flex:1,padding:5,border:"1px solid #000"}}><option>Global</option>{props.map(p=><option key={p.id}>{p.nom}</option>)}</select><select value={selVandPrix} onChange={e=>setSelVandPrix(e.target.value)} style={{flex:1,padding:5,border:"1px solid #000"}}><option>Tous</option>{vands.map(v=><option key={v.id}>{v.nom}</option>)}</select></div>{Object.entries(DEF_PRIX).map(([k,v])=><div key={k} style={{display:"flex",justifyContent:"space-between",marginTop:5,borderBottom:"1px solid #ccc"}}><span>{k}</span><input type="number" value={prix[k]} onChange={e=>setPrix({...prix,[k]:parseInt(e.target.value)||0})} style={{width:70,padding:4,border:"2px solid #000"}}/></div>)}<div style={{fontSize:9,marginTop:5}}>1er 50 - 2e 20 - 3e 10 - M1 1000 - M2 1000 - M3 1000 - L3 500 - L4 5000 - L5 25000</div></div>}

  {tab==="PARAM"&&<div style={{marginTop:10,border:"2px solid #000",padding:8}}><b>Paramètres</b><div style={{marginTop:8}}>Modpas super-admin (modifiable)<input value={superPass} onChange={e=>{setSuperPass(e.target.value);localStorage.setItem("SUP_PASS",e.target.value)}} style={{width:"100%",padding:8,border:"2px solid #000",marginTop:3}}/></div><div style={{marginTop:10}}>Ajoute logo (foto) - pou ki proprio<select value={selEntProp} onChange={e=>setSelEntProp(e.target.value)} style={{width:"100%",padding:6,border:"1px solid #000",marginTop:4}}><option>Global</option>{props.map(p=><option key={p.id}>{p.nom}</option>)}</select><input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>{const nl={...logos,[selEntProp]:r.result};setLogos(nl);localStorage.setItem("LOGOS",JSON.stringify(nl))};r.readAsDataURL(f)}}} style={{marginTop:5}}/><div style={{marginTop:5}}>{logos[selEntProp]&&<img src={logos[selEntProp]} style={{width:80,height:80,objectFit:"contain",border:"1px solid #000"}}/>}</div></div><div style={{marginTop:10,border:"1px solid #000",padding:6}}><b>Modifye antèt - Proprio chwazi</b><div style={{marginTop:5}}><label><input type="checkbox" checked={entete.logo} onChange={e=>setEntete({...entete,logo:e.target.checked})}/> Logo</label><br/><label><input type="checkbox" checked={entete.nom} onChange={e=>setEntete({...entete,nom:e.target.checked})}/> Non antrepriz</label><br/><label><input type="checkbox" checked={entete.dat} onChange={e=>setEntete({...entete,dat:e.target.checked})}/> Dat</label><br/><label><input type="checkbox" checked={entete.tiraj} onChange={e=>setEntete({...entete,tiraj:e.target.checked})}/> Tiraj</label><br/><label><input type="checkbox" checked={entete.vande} onChange={e=>setEntete({...entete,vande:e.target.checked})}/> Vandè</label><br/><label><input type="checkbox" checked={entete.id} onChange={e=>setEntete({...entete,id:e.target.checked})}/> Id ticket</label></div></div><div style={{marginTop:10}}>Tèks pye paj la<textarea value={footer} onChange={e=>{setFooter(e.target.value);localStorage.setItem("FOOTER",e.target.value)}} style={{width:"100%",padding:8,border:"2px solid #000",height:60,marginTop:4}}></textarea></div></div>}
 </div>)
}
